# opensearch version: 
#     3.0.0, 3.1.0, 3.2.0, 3.3.2, 3.4.0
engineVersion=os:3.4.0
org.gradle.jvmargs=-XX:MaxMetaspaceSize=350m \
  --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
org.gradle.caching=true
org.gradle.parallel=true
pluginName=analysis-sudachi
pluginVersion=3.4.1-SNAPSHOT
